=== madacruz/L3_Informatique_Mathematiques_Decision_Donnees/Données Semi Structurées/Donnees_semi_structurees-master/TD2_2020-01-27/solutions/cv.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT cv (coordonnees,lesFormations,lesExperiences?,activites?,langues?,connaissancesInfo?) >
<!ELEMENT coordonnees (nom,prenom,adresse,dateDeNaissance,tel,email) >
<!ELEMENT nom (#PCDATA) >
<!ELEMENT prenom (#PCDATA) >
<!ELEMENT dateDeNaissance (#PCDATA) >
<!ELEMENT tel (#PCDATA) >
<!ELEMENT email (#PCDATA) >
<!ELEMENT adresse (numero,voie,codepostal,ville) >
<!ELEMENT numero (#PCDATA) >
<!ELEMENT voie (#PCDATA) >
<!ELEMENT codepostal (#PCDATA) >
<!ELEMENT ville (#PCDATA) >
<!ELEMENT lesFormations (formation*) >
<!ELEMENT formation (annee,diplome,lieu,mention?) >
<!ELEMENT annee (#PCDATA) >
<!ELEMENT diplome (#PCDATA) >
<!ELEMENT lieu (#PCDATA) >
<!ELEMENT mention (#PCDATA) >
<!ELEMENT lesExperiences (experience*) >
<!ELEMENT experience (annee, libelle, lieu, descriptif?) >
<!ELEMENT libelle (#PCDATA) >
<!ELEMENT descriptif (#PCDATA) >
<!ELEMENT activites (#PCDATA) >
<!ELEMENT langues (langue*) >
<!ELEMENT langue EMPTY>
<!ATTLIST langue nom CDATA #REQUIRED>
<!ATTLIST langue parle (oui|non) #IMPLIED> 
<!ATTLIST langue ecrit (oui|non) #IMPLIED>

=== madacruz/L3_Informatique_Mathematiques_Decision_Donnees/Données Semi Structurées/Donnees_semi_structurees-master/TD2_2020-01-27/solutions/cv.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE address SYSTEM "cv.dtd">
<cv>
	<coordonnees>
		<nom> Napolitano </nom>
		<prenom> Beatrice </prenom>
		<adresse>
			<numero> 00 </numero>
			<voie> Rue de la pizza </voie>
			<codepostal> 75000 </codepostal>
			<ville> Paris </ville>
		</adresse>
		<dateDeNaissance> 16 Novembre 1900 </dateDeNaissance>
		<tel> 06 12345678</tel>
		<email>beatrice.napolitano@dauphine.fr</email>
	</coordonnees>

	<lesFormations>
		<formation>
			<annee>2006-2011</annee>
			<diplome>Baccalaureat</diplome>
			<lieu>Cosenza</lieu>
		</formation>
		<formation>
			<annee>2011-2014</annee>
			<diplome>Bachelor’s Degree in Computer Engineering</diplome>
			<lieu>Cosenza</lieu>
		</formation>
		<formation>
			<annee>2014-2018</annee>
			<diplome>Master’s Degree in Computer Engineering</diplome>
			<lieu>Cosenza</lieu>
		</formation>
	</lesFormations>

	<lesExperiences>
		<experience>
			<annee>2013</annee>
			<libelle>Exchange student - Warsaw University of Technology</libelle>
			<lieu>Warsaw</lieu>
		</experience>
		<experience>
			<annee>2015</annee>
			<libelle>Exchange student - University of Rhode Island</libelle>
			<lieu>Rhode Island</lieu>
		</experience>
		<experience>
			<annee>2017</annee>
			<libelle>Visiting student - Université Toulouse I Capitole</libelle>
			<lieu>Toulouse</lieu>
		</experience>
	</lesExperiences>

</cv>
